/**
 * 픽셀 캐릭터 데이터. 글자 = 팔레트 키, '.' = 투명. 캔버스 44×48, 본체는 x=4 부터.
 * 레벨 장식은 작은 조각을 좌표에 얹는다.
 */
export type Gender = "m" | "f";

export const PX_W = 44;
export const PX_H = 48;
const BODY_X = 4;

const FEMALE = `
................................
................................
...........OOOOOOOOOO...........
.........OOHHHHHHHHHHOO.........
........OHHHHHHHHHHHHHHO........
.......OHHHHhhHHHHHHHHHHO.......
.......OHHHhhHHHHHHHHHHHO.......
......OHHHHhHHHHHHHHHHHHHO......
......OHHHOOKKKKKKKKOOHHHO......
......OHHOKKKKKKKKKKKKOHHO......
......OHHOKKKKKKKKKKKKOHHO......
......OHHOKKOEKKKKEOKKOHHO......
......OHHOKKEEKKKKEEKKOHHO......
......OHHOCCKKKKKKKKCCOHHO......
......OHHOKKKKKMMKKKKKOHHO......
......OHHOKKKKKKKKKKKKOHHO......
......OHHHOKKKKKKKKKKOHHHO......
......OHHHHOOKKKKKKOOHHHHO......
......OHHHHHHOkKKkOHHHHHHO......
......OHHHHHOSSSSSSSOHHHHO......
......OHHHHOSSSSSSSSSOHHHO......
......OHHHOASSSSSSSSSAOHHO......
......OHHOAASSSSSSSSSAAOHO......
......OHHOAAsSSSSSSSsAAOHO......
......OHHOAAsSSSSSSSsAAOHO......
......OHHOAAsSSSSSSSsAAOHO......
......OHOaAAsSSSSSSSsAAaOHO.....
......OHOaAAsSSSSSSSsAAaOHO.....
.......OOaAAsSSSSSSSsAAaOO......
........OKKOsSSSSSSSsOKKO.......
........OKKOssSSSSSssOKKO.......
........OOOOPPPPPPPPPOOOO.......
...........OPPPPPPPPPO..........
...........OPpPPPPPpPO..........
...........OPPPPPPPPPO..........
...........OPpPPPPPpPO..........
...........OOOOOOOOOOO..........
............OKKOOOKKO...........
............OKKO.OKKO...........
............OKKO.OKKO...........
............OkKO.OKkO...........
............OBBO.OBBO...........
............OBBO.OBBO...........
............ObBO.OBbO...........
...........OBBBO.OBBBO..........
...........OOOOO.OOOOO..........
................................
................................
`;

const MALE = `
................................
................................
...........OOOOOOOOOO...........
..........OHHHHHHHHHHO..........
.........OHHHhhHHHHHHHO.........
.........OHHhhHHHHHHHHO.........
.........OHHHHHHHHHHHHO.........
.........OHHOOOOOOOOHHO.........
.........OHOKKKKKKKKOHO.........
.........OOKKKKKKKKKKOO.........
..........OKKKKKKKKKKO..........
..........OKKOEKKKKEOKO.........
..........OKKEEKKKKEEKO.........
..........OCCKKKKKKKKCCO........
..........OKKKKKMMKKKKO.........
..........OKKKKKKKKKKKO.........
...........OKKKKKKKKKKO.........
...........OOOKKKKKKOOO.........
.............OkKKKkO............
..........OOOSSSSSSSOOO.........
.........OSSSSSSSSSSSSSO........
........OASSSSSSSSSSSSSAO.......
........OAASSSSSSSSSSSAAO.......
........OAAsSSSSSSSSSsAAO.......
........OAAsSSSSSSSSSsAAO.......
........OAAsSSSSSSSSSsAAO.......
.......OaAAsSSSSSSSSSsAAaO......
.......OaAAsSSSSSSSSSsAAaO......
.......OaAAsSSSSSSSSSsAAaO......
........OKKOsSSSSSSSSsOKKO......
........OKKOssSSSSSSssOKKO......
........OOOOPPPPPPPPPPOOOO......
...........OPPPPPPPPPPO.........
...........OPPPPPPPPPPO.........
...........OPpPPOOPPpPO.........
...........OPPPPO.OPPPO.........
...........OPPPPO.OPPPO.........
...........OPpPPO.OPpPO.........
...........OPPPPO.OPPPO.........
...........OPPPPO.OPPPO.........
...........OOOOOO.OOOOO.........
...........OBBBBO.OBBBBO........
...........OBWWBO.OBWWBO........
..........OBBBBBO.OBBBBBO.......
..........OOOOOOO.OOOOOOO.......
................................
................................
................................
`;

const DINO = `
...OOOO.....
..ORROOO....
.ORRGGGOO...
.OGGGGGGGO..
OGGEGGGEGGO.
OGGGGGGGGGO.
OGGGMMMGGGO.
.OGGGGGGGO..
.ORRRRRRRO..
.ORWRRRWRO..
.ORRRRRRRO..
..OGGOGGO...
..OGGOGGO...
..OOO.OOO...
`;

const BADGE = `
WWWW
WRRW
WRWW
`;
const SCARF_F = `
RRWWRRWWRRWW
WWRRWWRRWWRR
`;
const SCARF_TAIL = `
RW
WR
RW
WR
RW
`;
const ARMBAND = `
YY
YY
`;
const TROPHY = `
.YYY.
YyYYY
.YYY.
..y..
.yyy.
`;
const CROWN = `
Y.Y.Y
YYYYY
yyyyy
`;
const FLAME_L = `
..N...
.NF...
.NFN..
NFFN..
NFFNN.
NNFFN.
.NNNN.
..NN..
`;
const SPARK = `
.F.
FFF
.F.
`;

const BASE_PALETTE: Record<string, string> = {
  O: "#262222", K: "#f6d7c3", k: "#e3b9a1", E: "#2a2420", M: "#d9586a", C: "#f4a9b3",
  W: "#ffffff", G: "#5fcf7a", R: "#e4002b", Y: "#f3c84b", y: "#c99a16", N: "#ff7a1a", F: "#ffe08a", T: "#8fd3ff",
};

export function palette(level: number, gender: Gender): Record<string, string> {
  const p = { ...BASE_PALETTE };
  p.H = gender === "f" ? "#1e1a1f" : "#2d2320";
  p.h = gender === "f" ? "#3b3340" : "#4a3a34";
  if (level >= 2) {
    p.S = "#e4002b"; p.s = "#b30021";
    [p.A, p.a] = level >= 3 ? ["#ffffff", "#d9d9d9"] : ["#e4002b", "#b30021"];
  } else {
    p.S = "#dfe9f3"; p.s = "#b9c8d8"; p.A = "#dfe9f3"; p.a = "#b9c8d8";
  }
  [p.P, p.p] = gender === "f" ? ["#2b2b33", "#1b1b22"] : ["#2f3a4d", "#222a39"];
  [p.B, p.b] = level >= 5 ? ["#f3c84b", "#c99a16"] : ["#1f1d22", "#111014"];
  return p;
}

type Cell = { x: number; y: number; k: string };

function rows(s: string) {
  return s.replace(/^\n+|\n+$/g, "").split("\n");
}

function stamp(out: Map<string, string>, art: string, ox: number, oy: number) {
  rows(art).forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const k = row[x];
      if (k !== ".") out.set(`${ox + x},${oy + y}`, k);
    }
  });
}

/** 레벨·성별·기분에 따라 합성한 픽셀 셀 목록 */
export function composeCells(level: number, gender: Gender, mood: "happy" | "sad" = "happy"): Cell[] {
  const L = Math.max(1, level);
  const out = new Map<string, string>();
  const f = gender === "f";

  if (L >= 10) { stamp(out, FLAME_L, 0, 26); stamp(out, FLAME_L, 37, 16); }
  if (L >= 6) stamp(out, DINO, 32, 33);
  stamp(out, f ? FEMALE : MALE, BODY_X, 0);
  if (L >= 3) stamp(out, BADGE, BODY_X + (f ? 13 : 13), f ? 21 : 21);
  if (L >= 4) { stamp(out, SCARF_F, BODY_X + (f ? 11 : 10), f ? 18 : 18); stamp(out, SCARF_TAIL, BODY_X + (f ? 21 : 21), f ? 20 : 20); }
  if (L >= 5) stamp(out, ARMBAND, BODY_X + (f ? 9 : 9), f ? 24 : 24);
  if (L >= 7) stamp(out, TROPHY, BODY_X + (f ? 7 : 7), f ? 25 : 25);
  if (L >= 8) { stamp(out, SPARK, 1, 6); stamp(out, SPARK, PX_W - 4, 12); stamp(out, SPARK, 2, 22); }
  if (L >= 9) stamp(out, CROWN, BODY_X + (f ? 13 : 13), 0);
  if (mood === "sad") { out.set(`${BODY_X + (f ? 12 : 12)},${f ? 14 : 14}`, "T"); out.set(`${BODY_X + (f ? 12 : 12)},${f ? 15 : 15}`, "T"); }

  const cells: Cell[] = [];
  for (const [key, k] of out) {
    const [x, y] = key.split(",").map(Number);
    cells.push({ x, y, k });
  }
  return cells;
}

/** 같은 색의 가로 연속 픽셀을 한 사각형으로 합친다 (SVG 요소 수 절약) */
export function composeRuns(level: number, gender: Gender, mood: "happy" | "sad" = "happy"): { x: number; y: number; w: number; color: string }[] {
  const pal = palette(level, gender);
  const grid = new Map<string, string>();
  for (const c of composeCells(level, gender, mood)) grid.set(`${c.x},${c.y}`, pal[c.k] ?? "#ff00ff");
  const runs: { x: number; y: number; w: number; color: string }[] = [];
  for (let y = 0; y < PX_H; y++) {
    let x = 0;
    while (x < PX_W) {
      const color = grid.get(`${x},${y}`);
      if (!color) { x++; continue; }
      let w = 1;
      while (x + w < PX_W && grid.get(`${x + w},${y}`) === color) w++;
      runs.push({ x, y, w, color });
      x += w;
    }
  }
  return runs;
}
